### ISSUE TITLE
Common properties for schema:Person would be nice of they were added

### ISSUE THREAD

**Issue by summercms** [schemaorg/suggestions-questions-brainstorming#3]
Hi,

There are many common fields not included with this taxology and I just thought I'd suggest some common property fields to be added to the class `Person`

- Age

- Weight

- Blood Type

- Star Sign

- Measurements

- Cup Size

etc.

For example:

```html
<script type="application/ld+json">
    {
      "@context": "http://schema.org/",
      "@type": "Person",
      "image": "http://example.com/images/profile.jpg",
      "name": "Claire Smith",
      "jobTitle": "Developer example for schema dot org",
      "age": 21,
      "height": "160cm",
      "weight": "46Kg",
      "bloodType": "O",
      "starSign": "Cancer",
      "measurements": "36–29–38",
      "cupSize": "C",
      "address": {
        "@type": "PostalAddress",
        "addressLocality": "Briar Park",
        "addressRegion": "Manitoba"
      },
      "email": "mailto:example@nothing.com"
    }
</script>
```

I thought `FOAF` was brought over to schema and I'm surprised `age` is not included: http://xmlns.com/foaf/spec/#term_age

**Comment by danbri** [comment]
ok, instead of being the 2581-th issue in the old issue tracker, we are now the 3rd issue in the new https://github.com/schemaorg/suggestions-questions-brainstorming/issues tracker.

This should not limit discussions in any way, but it will also hopefully help separate discussions of general improved expressivity, from discussions motivated by a consuming application.  Schema.org has always prioritized the latter, but we never made a good structure for the open-ended proposals like this. There are so many different things you could say about a person, e.g. medical information, genealogy, their interests etc., that we need some scoping mechanism to decide which go into schema.org. That scoping mechanism has historically been the simple question of "is anyone going to build something explicitly using this data?". So - what apps do we have in mind here?

**Comment by summercms** [comment]
Added a suggestion to help you, with your 1000 open issue problem.
